import type {NextPage} from 'next'
import Head from 'next/head'
import Post from 'components/blocks/post'
import ListControls from 'components/blocks/listControls'
import styles from 'styles/Home.module.scss'
import React, {
  ChangeEvent,
  FormEvent,
  SetStateAction,
  useState
} from "react"
import {useFilter} from "lib/hooks/useFilter";
import {IPost} from "lib/types/IPost"

const apiUrl = 'http://localhost:3000'

const Home: NextPage = (props: any) => {
  const [userSearchQuery, setUserSearchQuery] = useState('')
  const [userSort, setUserSort] = useState<'ASC' | 'DESC'>('ASC')
  const [userSearchField, setSearchField] = useState<'description' | 'title'>('description')
  const filteredPosts = useFilter<IPost>(props.data.posts, {
    sort: userSort,
    filter: {
      name: userSearchField,
      value: userSearchQuery
    }
  })

  function setSearch (e: FormEvent) {
    setUserSearchQuery((e.target as HTMLInputElement).value)
  }
  function setSort (e: ChangeEvent) {
    setUserSort(((e.target as HTMLSelectElement).value as SetStateAction<'ASC' | 'DESC'>))
  }
  function setField (e: ChangeEvent) {
    setSearchField(((e.target as HTMLSelectElement).value as SetStateAction<'description' | 'title'>))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <ListControls
          setSort={setSort}
          setField={setField}
          setSearch={setSearch}
          searchValue={userSearchQuery}
        />

        {filteredPosts.length ?
          (<ul className={styles.posts}>
            {filteredPosts.map((post: IPost) => {
              return (
                <Post post={post} key={post.id}/>
              )}
            )}
          </ul>) :
          <p>Nothing here yet</p>
        }

      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch(`${apiUrl}/api/posts`)
      .then((res) => res.json())
  const data = JSON.parse(res)

  return {
    props: {
      data
    }
  }
}

export default Home
